@url_dev = http://localhost:2811/api/v1

### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 1234567890abcdef

{
    "name": "Shop5",
    "email": "shop5@gmail.com",
    "password": "12345678"
}
   


